Use next() instead of calling .next()
this fixes:

>           fip = (ip for ip in self.api.floating_ips.list()
                   if ip.instance_id is None).next()
E                  AttributeError: 'generator' object has no attribute 'next'